# 📊 Python for Data Science - Complete Foundation

---

## 🎯 What You'll Master in This Module

This comprehensive notebook will take you from Python basics to data science fundamentals. You'll learn the two most critical libraries that power 90% of data science work:

### 📚 Module Structure

**Part 1: NumPy - Numerical Python** ⚡
- Creating and manipulating arrays (1D, 2D, multi-dimensional)
- Array operations and broadcasting
- Mathematical operations on arrays
- Array reshaping and manipulation
- Why NumPy is 100x faster than Python lists

**Part 2: Pandas - Data Analysis Powerhouse** 🐼
- Series vs DataFrames (when to use each)
- Reading data from CSV files
- Data selection and filtering (loc, iloc, boolean indexing)
- Sorting and grouping data
- Data aggregation and statistical summaries

---

## 🚀 Why This Matters

**NumPy** is the foundation of:
- Machine Learning (TensorFlow, PyTorch)
- Scientific Computing
- Image Processing
- Financial Analysis

**Pandas** is essential for:
- Data Cleaning (80% of a data scientist's time!)
- Exploratory Data Analysis (EDA)
- Business Intelligence
- Preparing data for Machine Learning

---

## 📋 Prerequisites

✅ Basic Python knowledge (lists, loops, functions)  
✅ Understanding of basic math operations  
✅ Familiarity with CSV files (optional but helpful)  

---

## 🛠️ Required Libraries

```python
# Install required packages (run once)
pip install numpy pandas
```

---

## 🗺️ Learning Path

```
NumPy Basics → Arrays → Operations → Broadcasting
     ↓
Pandas Series → DataFrames → Data Loading
     ↓
Data Selection → Filtering → Sorting → Grouping
     ↓
Statistical Analysis → Practice Projects
```

**💡 Pro Tip:** Run each cell as you go. Experiment by changing values to see what happens!

---

Let's begin your data science journey! 🎓

---

# Part 1: NumPy - Numerical Python ⚡

## 📦 What is NumPy?

NumPy (Numerical Python) is the foundation of scientific computing in Python. It provides:
- **N-dimensional arrays** - Store large amounts of data efficiently
- **Vectorized operations** - Perform calculations 100x faster than Python loops
- **Mathematical functions** - Built-in support for linear algebra, statistics, etc.

### 🎯 Why NumPy?

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Speed | Slow (loop-based) | **100x Faster** |
| Memory | High | **Low (50% less)** |
| Operations | One-by-one | **Vectorized** |
| Data Types | Mixed | Homogeneous (same type) |

---

## 🔢 Creating NumPy Arrays

Arrays come in different dimensions:
- **1D Array** - Like a list: `[1, 2, 3, 4]`
- **2D Array** - Like a table: `[[1, 2], [3, 4]]`
- **3D+ Array** - For images, videos, complex data

In [4]:
# Import NumPy - the standard alias is 'np'
import numpy as np

# 1D Array: Single row of data (like a Python list, but faster)
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D Array: Table-like structure with rows and columns
# Think of it as a matrix or spreadsheet
arr2 = np.array([[1, 2], [3, 4]])
print("\n2D Array:")
print(arr2)

# Note: All elements must be the same data type (homogeneous)
# NumPy automatically converts to the most appropriate type

[1 2 3 4]
[[1 2]
 [3 4]]

In [5]:
print(type(arr1))

<class 'numpy.ndarray'>

In [6]:
print(arr1.shape)

print(arr2.shape)

(4,)
(2, 2)

In [7]:
print(arr1[0])

1

In [10]:
print(arr2[0][0])

1

---

## ⚡ NumPy Math Operations - The Power of Vectorization

### Why Vectorization Matters

Instead of looping through each element (slow), NumPy applies operations to **entire arrays at once** (fast)!

**Example:**
```python
# Python way (SLOW) ❌
result = []
for x in [1, 2, 3]:
    result.append(x * 2)

# NumPy way (FAST) ✅
result = np.array([1, 2, 3]) * 2
```

### Common Operations

In [11]:
# Create an array of numbers
arr = np.array([10, 20, 30])

# SCALAR OPERATIONS: Apply operation to every element

# Addition: Add 5 to each element
print("Original:", arr)
print("Add 5:", arr + 5)  # [15, 25, 35]

# Multiplication: Multiply each element by 5
print("Multiply by 5:", arr * 5)  # [50, 100, 150]

# Division: Divide each element by 10
print("Divide by 10:", arr / 10)  # [1.0, 2.0, 3.0]

# Note: Original array 'arr' is NOT modified (NumPy creates new arrays)

[15 25 35]
[ 50 100 150]
[1. 2. 3.]

In [12]:
np.sum(arr)

60

In [13]:
np.mean(arr)

20.0

In [14]:
a = np.array([10, 20, 30])

b = np.array([1, 2, 3])

In [15]:
c = a + b

In [16]:
print(c)

[11 22 33]

In [19]:
## Without numpy:
a = [1, 2, 3]
b = [4, 5, 6]

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

In [20]:
print(result)

[5, 7, 9]

In [21]:
a + b

[1, 2, 3, 4, 5, 6]

### Exercise
1. Create a 1D and 2D array

2. Slice a 2D array to get a sub-matrix

3. Perform element-wise addition and multiplication

4. Use np.arange() and np.linspace() to generate number ranges

5. Calculate average marks of 5 students using NumPy arrays

---

## 🔄 Reshape Arrays - Change Dimensions

### Why Reshape?

Machine learning algorithms often require specific shapes:
- **Images**: 1D array → 2D/3D (height × width × channels)
- **Models**: Must match input/output dimensions
- **Data preprocessing**: Transform data for analysis

### Rules for Reshaping

✅ **Total elements must remain the same**
- 6 elements: (6,) → (2, 3) ✓
- 6 elements: (6,) → (3, 2) ✓
- 6 elements: (6,) → (2, 4) ✗ (needs 8 elements)

Formula: `rows × columns = total elements`

In [1]:
import numpy as np

# Original 1D array with 6 elements
a = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2 rows × 3 columns (2×3 = 6 elements ✓)
b = a.reshape(2, 3)

# You can also reshape to:
c = a.reshape(3, 2)  # 3 rows × 2 columns
d = a.reshape(6, 1)  # Column vector (6 rows × 1 column)

In [6]:
print("Original:", a)

print("Reshaped (2x3):\n", b)

Original: [1 2 3 4 5 6]
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]

---

## 📡 Broadcasting - NumPy's Superpower

### What is Broadcasting?

Broadcasting allows NumPy to perform operations on arrays of **different shapes** without copying data!

**Example:**
```python
# Array: (2×3)     [[1, 2, 3],
#                   [4, 5, 6]]
#
# Vector: (3,)     [10, 20, 30]
#
# Result: (2×3)    [[11, 22, 33],
#                   [14, 25, 36]]
```

### Broadcasting Rules

1. If arrays have different dimensions, **pad smaller array's shape with 1s** on the left
2. Arrays are compatible if dimensions are **equal OR one of them is 1**
3. Arrays with dimension 1 are **stretched** to match the other array

### Common Use Cases

- Add a constant to each row
- Normalize data (subtract mean, divide by std)
- Image processing (apply filters)

In [7]:
# 2D array (2 rows × 3 columns)
a = np.array([[1, 2, 3], [4, 5, 6]])

# 1D array (3 elements) - will be broadcast to match 'a'
b = np.array([10, 20, 30])

# NumPy automatically broadcasts 'b' to each row of 'a'
# Row 1: [1, 2, 3] + [10, 20, 30] = [11, 22, 33]
# Row 2: [4, 5, 6] + [10, 20, 30] = [14, 25, 36]
print("Result of broadcasting:")
print(a + b)

# Without broadcasting, you'd need nested loops! 🐌

[[11 22 33]
 [14 25 36]]

## Pandas

In [9]:
import pandas as pd

---

## 📊 Pandas Series - One-Dimensional Labeled Array

### What is a Series?

A Series is like a **single column from Excel** with:
- **Values** - The actual data
- **Index** - Row labels (can be custom or auto-generated)

### When to Use Series?

✅ Single variable (e.g., student marks, stock prices)  
✅ Time series data (dates as index)  
✅ Extracting a column from a DataFrame

In [10]:
# Create a Series with custom index (student names)
s1 = pd.Series(
    [85, 90, 78, 92],  # Values (marks)
    index=["Aarav", "Meera", "Divya", "Ravi"]  # Custom labels
)

print(s1)

# Access by label: s1['Aarav'] → 85
# Access by position: s1[0] → 85

Aarav    85
Meera    90
Divya    78
Ravi     92
dtype: int64

In [11]:
data = [10, 20, 30, 40]

pd.Series(data)

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
# Create a DataFrame from a dictionary
# Keys = Column names
# Values = Lists of data
data = {
    "Name": ["Aarav", "Divya", "Meera"],  # Column 1
    "Marks": [85, 92, 78]  # Column 2
}

# Note: All lists must have the same length!

In [15]:
df = pd.DataFrame(data)

print(df)

    Name  Marks
0  Aarav     85
1  Divya     92
2  Meera     78

In [16]:
df = pd.DataFrame(data, index = ['s1', 's2', 's3'])

print(df)

     Name  Marks
s1  Aarav     85
s2  Divya     92
s3  Meera     78

In [17]:
df['Name']

s1    Aarav
s2    Divya
s3    Meera
Name: Name, dtype: object

In [19]:
df[["Name", "Marks"]]

     Name  Marks
s1  Aarav     85
s2  Divya     92
s3  Meera     78

### Series vs DataFrame - Key Differences

| Feature        | Series                 | DataFrame                             |
| -------------- | ---------------------- | ------------------------------------- |
| Dimensions     | 1D                     | 2D (Rows × Columns)                   |
| Data type      | Like a single column   | Like a full table                     |
| Access pattern | `s['A']`, `s[1]`       | `df['Name']`, `df.loc[]`, `df.iloc[]` |
| Use case       | Single variable/column | Full dataset with multiple variables  |

pd.Series()
pd.DataFrame()
.loc[] -> Access by index label
.iloc[] -> Access by numeric index

---

## 📂 Reading Data from CSV Files

### What is CSV?

**CSV (Comma-Separated Values)** is the most common file format for data:
```csv
Name,Age,City
Aarav,25,Mumbai
Meera,30,Delhi
```

### Why CSV?

✅ Universal format (works everywhere)  
✅ Lightweight (smaller than Excel)  
✅ Easy to share and version control  
✅ Readable by all data tools  

### Common Parameters

```python
pd.read_csv('file.csv', 
    sep=',',           # Delimiter (default: comma)
    index_col='Name',  # Set a column as index
    na_values=['NA']   # Treat 'NA' as missing
)
```

In [21]:
df = pd.read_csv("students.csv")

In [29]:
df

    Name Class  Marks Grade
0  Aarav   10A     85     B
1  Meera   10A     90     A
2  Divya   10B     78    B+
3   Ravi   10B     92    A+
4  Sneha   10C     67     C
5  Karan   10C     88     A

In [23]:
df.tail()

    Name Class  Marks Grade
1  Meera   10A     90     A
2  Divya   10B     78    B+
3   Ravi   10B     92    A+
4  Sneha   10C     67     C
5  Karan   10C     88     A

### Access columns & rows

In [24]:
df['Name']

0    Aarav
1    Meera
2    Divya
3     Ravi
4    Sneha
5    Karan
Name: Name, dtype: object

In [25]:
df[['Name', 'Class']]

    Name Class
0  Aarav   10A
1  Meera   10A
2  Divya   10B
3   Ravi   10B
4  Sneha   10C
5  Karan   10C

In [26]:
df.iloc[0]

Name     Aarav
Class      10A
Marks       85
Grade        B
Name: 0, dtype: object

In [27]:
print(df.loc[1])  #label based location

Name     Meera
Class      10A
Marks       90
Grade        A
Name: 1, dtype: object

In [30]:
df.loc[[0, 3, 5]]

    Name Class  Marks Grade
0  Aarav   10A     85     B
3   Ravi   10B     92    A+
5  Karan   10C     88     A

In [31]:
df.loc[5, "Marks"]

88

In [32]:
df

    Name Class  Marks Grade
0  Aarav   10A     85     B
1  Meera   10A     90     A
2  Divya   10B     78    B+
3   Ravi   10B     92    A+
4  Sneha   10C     67     C
5  Karan   10C     88     A

In [34]:
df_named = pd.read_csv("students.csv", index_col = "Name")

df_named.head()

      Class  Marks Grade
Name
Aarav   10A     85     B
Meera   10A     90     A
Divya   10B     78    B+
Ravi    10B     92    A+
Sneha   10C     67     C

In [35]:
df_named.loc["Ravi"]

Class    10B
Marks     92
Grade     A+
Name: Ravi, dtype: object

In [36]:
df_named.loc["Ravi", "Grade"]

'A+'

### .iloc[] # Integer position-based access

In [38]:
df

    Name Class  Marks Grade
0  Aarav   10A     85     B
1  Meera   10A     90     A
2  Divya   10B     78    B+
3   Ravi   10B     92    A+
4  Sneha   10C     67     C
5  Karan   10C     88     A

In [39]:
df.iloc[0]

Name     Aarav
Class      10A
Marks       85
Grade        B
Name: 0, dtype: object

In [40]:
df.iloc[2:5]

    Name Class  Marks Grade
2  Divya   10B     78    B+
3   Ravi   10B     92    A+
4  Sneha   10C     67     C

In [41]:
df.iloc[3, 3]

'A+'

### Filtering Data

In [43]:
df

    Name Class  Marks Grade
0  Aarav   10A     85     B
1  Meera   10A     90     A
2  Divya   10B     78    B+
3   Ravi   10B     92    A+
4  Sneha   10C     67     C
5  Karan   10C     88     A

In [44]:
df[df['Marks'] > 80]

    Name Class  Marks Grade
0  Aarav   10A     85     B
1  Meera   10A     90     A
3   Ravi   10B     92    A+
5  Karan   10C     88     A

In [46]:
## Students with Grade A:

df[df["Grade"] == 'A']

    Name Class  Marks Grade
1  Meera   10A     90     A
5  Karan   10C     88     A

### Sorting Data

In [50]:
df.sort_values(by = "Marks", ascending = True)

    Name Class  Marks Grade
4  Sneha   10C     67     C
2  Divya   10B     78    B+
0  Aarav   10A     85     B
5  Karan   10C     88     A
1  Meera   10A     90     A
3   Ravi   10B     92    A+

In [51]:
df.sort_values(by = "Marks", ascending = False)

    Name Class  Marks Grade
3   Ravi   10B     92    A+
1  Meera   10A     90     A
5  Karan   10C     88     A
0  Aarav   10A     85     B
2  Divya   10B     78    B+
4  Sneha   10C     67     C

---

## 📊 Grouping Data with `groupby()` - Split-Apply-Combine

### What is GroupBy?

`groupby()` answers questions like:
- What's the **average salary per department**?
- How many **students in each class**?
- What's the **total sales by region**?

### The Split-Apply-Combine Pattern

```
1. SPLIT     → Group data by category (e.g., by 'Grade')
2. APPLY     → Calculate something for each group (mean, count, sum)
3. COMBINE   → Merge results into a summary table
```

### Common Aggregations

| Function | Purpose | Example |
|----------|---------|----------|
| `.count()` | Count non-null values | Students per class |
| `.mean()` | Average | Average marks per grade |
| `.sum()` | Total | Total sales per region |
| `.min()` / `.max()` | Min/Max values | Youngest/oldest in group |
| `.agg()` | Multiple aggregations | Mean + Max + Min together |

### Real-World Use Cases

📈 **Business Analytics**
```python
sales_df.groupby('Region')['Revenue'].sum()
```

🎓 **Education**
```python
students_df.groupby('Class')['Marks'].mean()
```

💰 **Finance**
```python
transactions_df.groupby('Category')['Amount'].agg(['sum', 'mean', 'count'])
```

In [57]:
df[['Grade', 'Marks']].groupby("Grade").count()

       Marks
Grade
A          2
A+         1
B          1
B+         1
C          1

In [58]:
summary = df.groupby("Class").agg({
    "Marks": ["mean", "max", "min"],
    "Name":"count"
})

print(summary)

      Marks          Name
       mean max min count
Class
10A    87.5  90  85     2
10B    85.0  92  78     2
10C    77.5  88  67     2

In [59]:
summary

      Marks          Name
       mean max min count
Class
10A    87.5  90  85     2
10B    85.0  92  78     2
10C    77.5  88  67     2

In [60]:
df.describe()

           Marks
count   6.000000
mean   83.333333
std     9.373722
min    67.000000
25%    79.750000
50%    86.500000
75%    89.500000
max    92.000000

## Practice Tasks
1. Create a CSV of 5 Indian students with Name, Class, Marks, Grade

2. Import it and print:

> - Only names with marks above 80

> - Count students per Grade using groupby()

> - Sort by Class

3. Use .describe() to get a full summary

---

---

# 🎓 Session Summary - Python for Data Science

## 📚 What We Covered Today

### Part 1: NumPy Mastery ⚡

#### Core Concepts
1. **Arrays** - Foundation of numerical computing
   - 1D, 2D, multi-dimensional arrays
   - 100x faster than Python lists
   - Homogeneous data type requirement

2. **Vectorized Operations** - No more loops!
   - Scalar operations: `arr + 5`, `arr * 2`
   - Element-wise operations: `arr1 + arr2`
   - Mathematical functions: `np.sum()`, `np.mean()`

3. **Array Manipulation**
   - Shape and dimensions: `.shape`, `.ndim`
   - Reshaping: `.reshape(rows, cols)`
   - Indexing: `arr[0]`, `arr[0][1]`

4. **Broadcasting** - NumPy's superpower
   - Operate on arrays of different shapes
   - Automatic dimension matching
   - Memory-efficient operations

---

### Part 2: Pandas Mastery 🐼

#### Core Concepts
1. **Data Structures**
   - **Series**: 1D labeled array (single column)
   - **DataFrame**: 2D labeled table (multiple columns)

2. **Data Import/Export**
   - Reading CSV: `pd.read_csv('file.csv')`
   - Setting index: `index_col='Name'`
   - Quick views: `.head()`, `.tail()`

3. **Data Selection**
   - **Column selection**: `df['Name']`, `df[['Name', 'Age']]`
   - **Label-based**: `.loc[row_label, col_label]`
   - **Position-based**: `.iloc[row_index, col_index]`

4. **Data Filtering**
   - Boolean indexing: `df[df['Marks'] > 80]`
   - Multiple conditions: `(condition1) & (condition2)`
   - Equality checks: `df[df['Grade'] == 'A']`

5. **Data Transformation**
   - Sorting: `.sort_values(by='column')`
   - Grouping: `.groupby('column')`
   - Aggregation: `.agg(['mean', 'max', 'min'])`

6. **Statistical Analysis**
   - Quick stats: `.describe()`
   - Count: `.count()`
   - Aggregations: `mean()`, `sum()`, `max()`, `min()`

---

## 🔑 Key Takeaways

### When to Use What?

| Task | Tool | Example |
|------|------|----------|
| Mathematical calculations | **NumPy** | Matrix multiplication, linear algebra |
| Tabular data analysis | **Pandas** | CSV files, Excel sheets, databases |
| Large numerical arrays | **NumPy** | Image processing, scientific computing |
| Data cleaning & preprocessing | **Pandas** | Handle missing values, duplicates |
| Group-based analysis | **Pandas** | Sales by region, students by class |
| Fast array operations | **NumPy** | Broadcasting, vectorization |

---

## 💡 NumPy vs Pandas - Decision Guide

### Use NumPy When:
✅ Working with numerical arrays  
✅ Need maximum performance (speed)  
✅ Mathematical/scientific computing  
✅ Building machine learning models  
✅ Image/signal processing  

### Use Pandas When:
✅ Working with CSV/Excel files  
✅ Need labeled data (row/column names)  
✅ Data cleaning and preprocessing  
✅ Exploratory Data Analysis (EDA)  
✅ Business intelligence reports  
✅ Time series analysis  

---

## 🚀 Essential Syntax Quick Reference

### NumPy Essentials
```python
# Creating arrays
np.array([1, 2, 3])              # From list
np.zeros((3, 3))                 # All zeros
np.ones((2, 4))                  # All ones
np.arange(0, 10, 2)              # Range [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)             # 5 evenly spaced values

# Operations
arr + 5                          # Scalar addition
arr1 + arr2                      # Element-wise
arr.reshape(2, 3)                # Change shape
np.sum(arr), np.mean(arr)        # Aggregations
```

### Pandas Essentials
```python
# Creating DataFrames
pd.Series([1, 2, 3])                    # Series
pd.DataFrame({'A': [1, 2], 'B': [3, 4]}) # DataFrame
pd.read_csv('file.csv')                  # From CSV

# Selection
df['column']                     # Single column
df[['col1', 'col2']]             # Multiple columns
df.loc[row_label, col_label]     # Label-based
df.iloc[0, 1]                    # Position-based

# Filtering & Analysis
df[df['Age'] > 25]               # Filter
df.sort_values(by='Name')        # Sort
df.groupby('Category').mean()    # Group + aggregate
df.describe()                    # Statistical summary
```

---

## 🎯 Practice Challenges

### Challenge 1: NumPy Array Mastery
1. Create a 3×4 array of random numbers (hint: `np.random.rand()`)
2. Reshape it to 2×6
3. Calculate the mean of each column
4. Find all elements greater than 0.5

### Challenge 2: Pandas Data Analysis
Using the `students.csv` file:
1. Load the data and set 'Name' as the index
2. Filter students with marks > 85
3. Group by 'Class' and calculate average marks
4. Sort by marks in descending order
5. Count how many students got each grade (A, B, C)

### Challenge 3: Real-World Application
Create a DataFrame with:
- 10 employees (Name, Department, Salary, Years)
- Calculate average salary per department
- Find highest paid employee in each department
- Add a bonus column (10% for >5 years, 5% otherwise)

---

## 📖 Next Steps in Your Journey

### Immediate Next Topics
1. **Data Visualization** 📊
   - Matplotlib (plotting library)
   - Seaborn (statistical visualizations)
   - Charts: line plots, bar charts, histograms

2. **Advanced Pandas** 🔥
   - Merging DataFrames (join, merge, concat)
   - Handling missing data (dropna, fillna)
   - Pivot tables and cross-tabulation
   - Time series analysis

3. **Data Cleaning** 🧹
   - Removing duplicates
   - Handling outliers
   - Data type conversions
   - String operations

### Long-Term Path
```
NumPy + Pandas (Foundation)
       ↓
Data Visualization (Matplotlib/Seaborn)
       ↓
Machine Learning (Scikit-learn)
       ↓
Deep Learning (TensorFlow/PyTorch)
```

---

## 📚 Learning Resources

### Official Documentation
- **NumPy**: https://numpy.org/doc/
- **Pandas**: https://pandas.pydata.org/docs/

### Practice Platforms
- **Kaggle**: Real datasets and competitions
- **DataCamp**: Interactive exercises
- **LeetCode**: Pandas practice problems

### Books
- "Python for Data Analysis" by Wes McKinney (Pandas creator!)
- "NumPy Beginner's Guide" by Ivan Idris

---

## 💪 You've Completed Python for Data Science Foundations!

### What You Can Now Do:
✅ Work with large numerical datasets efficiently  
✅ Load and analyze CSV files  
✅ Filter and transform data  
✅ Perform group-based analysis  
✅ Calculate statistical summaries  
✅ Build data analysis pipelines  

### Remember:
🧠 **Practice makes perfect** - Work with real datasets  
📊 **Visualization is next** - See your data come alive  
🔬 **Experiment freely** - Pandas is forgiving, try things out!  
🚀 **Keep building** - Each project makes you better  

---

**"Data is the new oil, but only if you know how to refine it."**

Keep learning, keep analyzing! 🎓📊🚀